In [2]:
import pandas as pd, matplotlib, numpy as np, seaborn as sb

In [3]:
import sklearn, imblearn, category_encoders, scipy

In [15]:
from sklearn.model_selection import train_test_split    # Divisão de dados em treino/teste
from sklearn.preprocessing import StandardScaler        # Padronização de features (Z-score)
from sklearn.impute import SimpleImputer               # Imputação de valores faltantes
from sklearn.linear_model import LogisticRegression    # Modelo de classificação linear
from sklearn.metrics import accuracy_score, confusion_matrix  # Métricas de avaliação

In [9]:
url = r'C:\Users\gabri\OneDrive\Documentos\MBA\Feature Engineering\FIAP-Feature-Engineering\aula-1-fundamentos-e-pre-processamento\datasets\heart_disease.csv'
df = pd.read_csv(url)

In [11]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,?,145.0,233.0,1.0,2.0,150.0,0.0,?,3.0,0.0,6.0,0
1,67.0,?,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,?,0.0,2.0,129.0,?,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,?,?,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    str
 1   sex       303 non-null    str
 2   cp        303 non-null    str
 3   trestbps  303 non-null    str
 4   chol      303 non-null    str
 5   fbs       303 non-null    str
 6   restecg   303 non-null    str
 7   thalach   303 non-null    str
 8   exang     303 non-null    str
 9   oldpeak   303 non-null    str
 10  slope     303 non-null    str
 11  ca        299 non-null    str
 12  thal      301 non-null    str
 13  target    303 non-null    int64
dtypes: int64(1), str(13)
memory usage: 33.3 KB

In [13]:
df.describe()

           target
count  303.000000
mean     0.937294
std      1.228536
min      0.000000
25%      0.000000
50%      0.000000
75%      2.000000
max      4.000000

In [16]:
X = df.drop('target', axis=1) if 'target' in df.columns else df.iloc[:, :-1]
y = df['target'] if 'target' in df.columns else df.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [17]:
X_train.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
132,?,1.0,2.0,130.0,204.0,0.0,2.0,202.0,0.0,?,?,0.0,3.0
202,57.0,1.0,3.0,150.0,126.0,?,0.0,173.0,0.0,0.2,1.0,1.0,7.0
196,69.0,1.0,1.0,160.0,234.0,1.0,2.0,131.0,0.0,0.1,2.0,1.0,3.0
75,65.0,0.0,3.0,160.0,360.0,?,2.0,151.0,0.0,0.8,1.0,0.0,3.0
176,52.0,?,4.0,108.0,233.0,1.0,0.0,147.0,0.0,0.1,?,?,7.0

In [18]:
X_train_clean = X_train.replace('?', np.nan)
X_train_clean = X_train_clean.apply(pd.to_numeric)

In [20]:
X_train_clean.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
count,221.000000,217.000000,217.000000,219.000000,218.000000,216.000000,219.000000,218.000000,220.000000,216.000000,218.000000,215.000000,216.000000
mean,54.914027,0.658986,3.082949,132.242009,246.683486,0.143519,0.986301,150.577982,0.331818,1.025926,1.605505,0.637209,4.712963
std,8.866014,0.475146,0.977778,18.047360,47.780757,0.351415,0.997609,21.954832,0.471940,1.196380,0.629803,0.890506,1.934033
min,34.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,90.000000,0.000000,0.000000,1.000000,0.000000,3.000000
25%,48.000000,0.000000,2.000000,120.000000,212.250000,0.000000,0.000000,138.000000,0.000000,0.000000,1.000000,0.000000,3.000000
50%,56.000000,1.000000,3.000000,130.000000,243.000000,0.000000,0.000000,153.000000,0.000000,0.750000,2.000000,0.000000,3.000000
75%,61.000000,1.000000,4.000000,140.000000,273.750000,0.000000,2.000000,167.750000,1.000000,1.600000,2.000000,1.000000,7.000000
max,77.000000,1.000000,4.000000,192.000000,417.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000,7.000000

In [21]:
X_test_clean = X_test.replace('?', np.nan)
X_test_clean = X_test_clean.apply(pd.to_numeric)

In [25]:
X_test_clean

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
179,NaN,1.0,NaN,130.0,246.0,1.0,2.0,173.0,0.0,0.0,1.0,3.0,NaN
228,NaN,1.0,4.0,110.0,206.0,0.0,2.0,108.0,1.0,0.0,2.0,1.0,3.0
111,56.0,NaN,4.0,125.0,249.0,1.0,2.0,144.0,1.0,1.2,2.0,1.0,3.0
246,NaN,NaN,4.0,100.0,NaN,0.0,0.0,156.0,0.0,0.1,1.0,1.0,7.0
60,51.0,0.0,4.0,NaN,305.0,0.0,0.0,142.0,1.0,NaN,2.0,0.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,62.0,1.0,2.0,128.0,208.0,1.0,2.0,140.0,0.0,0.0,1.0,0.0,NaN
104,49.0,1.0,3.0,120.0,188.0,0.0,0.0,139.0,0.0,NaN,2.0,3.0,7.0
300,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0
193,62.0,0.0,4.0,138.0,294.0,1.0,0.0,106.0,0.0,1.9,2.0,3.0,3.0
184,60.0,0.0,4.0,158.0,305.0,0.0,2.0,161.0,NaN,0.0,1.0,0.0,3.0

In [36]:
imputer = SimpleImputer(strategy='mean')

X_train_imputed = pd.DataFrame(imputer.fit_transform(X_train_clean), columns = X_train_clean.columns)
X_train_imputed

#Aplicar as mesmas alteraçoes no test
X_test_imputed = pd.DataFrame(imputer.transform(X_test_clean), columns = X_test_clean.columns)

In [37]:
X_test_imputed

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,54.914027,1.000000,3.082949,130.000000,246.000000,1.0,2.0,173.0,0.000000,0.000000,1.0,3.0,4.712963
1,54.914027,1.000000,4.000000,110.000000,206.000000,0.0,2.0,108.0,1.000000,0.000000,2.0,1.0,3.000000
2,56.000000,0.658986,4.000000,125.000000,249.000000,1.0,2.0,144.0,1.000000,1.200000,2.0,1.0,3.000000
3,54.914027,0.658986,4.000000,100.000000,246.683486,0.0,0.0,156.0,0.000000,0.100000,1.0,1.0,7.000000
4,51.000000,0.000000,4.000000,132.242009,305.000000,0.0,0.0,142.0,1.000000,1.025926,2.0,0.0,7.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,62.000000,1.000000,2.000000,128.000000,208.000000,1.0,2.0,140.0,0.000000,0.000000,1.0,0.0,4.712963
57,49.000000,1.000000,3.000000,120.000000,188.000000,0.0,0.0,139.0,0.000000,1.025926,2.0,3.0,7.000000
58,57.000000,1.000000,4.000000,130.000000,131.000000,0.0,0.0,115.0,1.000000,1.200000,2.0,1.0,7.000000
59,62.000000,0.000000,4.000000,138.000000,294.000000,1.0,0.0,106.0,0.000000,1.900000,2.0,3.0,3.000000
60,60.000000,0.000000,4.000000,158.000000,305.000000,0.0,2.0,161.0,0.331818,0.000000,1.0,0.0,3.000000

In [39]:
# Normalizaçao dos dados
scaler = StandardScaler(with_mean=False, with_std=True)
X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train_imputed), columns = X_train_imputed.columns)

X_test_scaled = pd.DataFrame(scaler.transform(X_test_imputed), columns = X_test_imputed.columns)

In [40]:
#Aplicar no modelo de Machine Learning

X_raw_train, X_raw_test = X_train_imputed, X_test_imputed
y_raw_train, y_raw_test = y_train, y_test

In [41]:
model_raw = LogisticRegression(max_iter = 1000, random_state = 42)
model_raw.fit(X_raw_train, y_raw_train)
y_pred_raw = model_raw.predict(X_raw_test)

c:\Users\gabri\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [45]:
accuracy_raw = accuracy_score(y_raw_test, y_pred_raw)
conf_matrix_raw = confusion_matrix(y_raw_test, y_pred_raw)